### ISSUE TITLE
Allow top-level literal assignments

### ISSUE THREAD

**Issue by ericcornelissen** [eramdam/eslint-plugin-top#1]
I started using this plugin but was surprised to find out it reports about top-level literal assignments to constants (e.g. `const bar = 1337;`). Since these can't be changed, I don't think they should be considered problematic (even considering the [ref](https://developpaper.com/explain-the-difference-between-commonjs-and-es6-modules-in-cyclic-loading-processing/) from [eslint-plugin-toplevel](https://github.com/HKalbasi/eslint-plugin-toplevel)). Do let me know if that assumption is wrong.

I think this could be achieved quite simply by adding a check `isLiteral` to  [`noTopLevelVariables.ts#L32-L42`](https://github.com/eramdam/eslint-plugin-top/blob/de3072d8e1aa41b636eb1c211c1d8460483007b6/lib/rules/noTopLevelVariables.ts#L32-L42) like:

```ts
const isMatching = Array.from(options.kind).includes(node.kind);
const isRequire =
  node.declarations[0].init?.type === 'CallExpression' &&
  node.declarations[0].init.callee.type === 'Identifier' &&
  node.declarations[0].init.callee.name === 'require';
const isLiteral =
  node.kind === 'const' &&
  node.declarations[0].init?.type === 'Literal';

if (isMatching && !isRequire && !isLiteral) {
  if (isTopLevel(node)) {
    context.report({node, messageId: 'message'});
  }
}
```

---

As a temporary solution, I started [a fork scoped to my personal npm namespace](https://github.com/ericcornelissen/eslint-plugin-top) with the above patch applied.

**Comment by eramdam** [comment]
I'll be honest, I completely forgot why/when I made this plugin so I don't really intend to maintain it much.
I'll probably archive it here on GitHub/remove it from npm so feel free to run your own fork.
